from flask import Flask, request, jsonify, render_template
import openai
import json

app = Flask(__name__)

# Set up OpenAI API key
openai.api_key = "YOUR_OPENAI_API_KEY"

# Define endpoint for tweet analysis
@app.route('/analyze_tweet', methods=['GET', 'POST'])
def analyze_tweet():
    if request.method == 'POST':
        # Get tweet URL from form data
        tweet_url = request.form['tweet_url']

        # Extract tweet ID from tweet URL
        tweet_id = tweet_url.split('/')[-1]

        # Get tweet text using Twitter API
        # (replace with your own Twitter API code)
        tweet_text = get_tweet_text(tweet_id)

        # Analyze tweet using GPT-3 model
        prompt = "Is the following tweet generated by AI?\n\n" + tweet_text + "\n\nProbability:"
        response = openai.Completion.create(engine="text-davinci-002", prompt=prompt, max_tokens=1)

        # Extract probability score from GPT-3 response
        probability = float(response.choices[0].text)

        # Render results page with probability score chart
        return render_template('results.html', probability=probability)
    else:
        # Render form page
        return render_template('form.html')

if __name__ == '__main__':
    app.run(debug=True)
